### PR TITLE
Update default.conf.template

### PR DESCRIPTION
**Pull request by bkuhl**
Currently there's an issue where requests don't get mapped to the fpm container other than for /healthcheck. This addresses that

### CODE REVIEW

**Comment by bkuhl** [comment]
📟

**Comment by johnfischelli** [comment]
After merging this change and #45 into the PVPC app repository, I'm noticing that the actual `infrastructure/nginx/default.conf` file that gets generated from the template is left as an uncommitted file in our repos.

Would it be safe to add that to the .gitignore, or should we just commit the file.

Does it matter either way?

**Comment by bkuhl** [comment]
It should be added to gitignore.  Committing it doesn't add any value since it's re-generated each time the container is rebuilt.

**Comment by johnfischelli** [comment]
👍 , that was my initial thought as well. Thanks!

**Pull request merged**
