### PR TITLE
Cache dependencies (NPM/Composer)

### PR DESCRIPTION
**Pull request by jmauerhan**

### CODE REVIEW

**Comment by bkuhl** [comment]
Jason didn't change the password.  I used the same creds to login to Dockerhub manually and they work fine.  We've encountered this same issue before.  The credentials randomly stop working on the API for a reason we're not sure of and after a while they'll start working again.  This is one of the reasons we've been favoring the idea of moving to Quay.io

**Comment by bkuhl** [comment]
I've contacted Docker support as I've now tried 3 sets of credentials, all of which are accepted on their web site but rejected when using the docker cli.  #WishWeUsedQuay

**Comment by bkuhl** [comment]
Other starter changes are passing now.  I believe this is merely a result of travis caching the environment variables to be re-used even when the build restarts.  I'm thinking we need a new commit hash on this PR to prove it.

**Comment by jmauerhan** [comment]
I had a similar issue on a project and it didn't work until I pushed a new commit to the PR. I'll do that here.

**Pull request closed without merging**
